# Generated by Django 5.0.3 on 2024-03-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='badcomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badcomputername', models.CharField(max_length=100)),
                ('badcomputerid', models.CharField(max_length=100)),
                ('badcomputeraddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blogcomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogcomputertitle', models.CharField(max_length=100)),
                ('blogcomputerid', models.CharField(max_length=100)),
                ('blogcomputerdetails', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='computerlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computername', models.CharField(max_length=100)),
                ('computerid', models.CharField(max_length=100)),
                ('computeraddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='goodcomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodcomputername', models.CharField(max_length=100)),
                ('goodcomputerid', models.CharField(max_length=100)),
                ('goodcomputeraddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='internationalcomputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internationalcomputername', models.CharField(max_length=100)),
                ('internationalcomputerid', models.CharField(max_length=100)),
                ('internationalcomputeraddress', models.CharField(max_length=100)),
            ],
        ),
    ]
