# Generated by Django 5.0.6 on 2024-06-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounterApp', '0003_customeusermodel_bmrcal'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriesmodel',
            name='CreateDate',
            field=models.DateField(null=True),
        ),
    ]
