# Generated by Django 5.0.4 on 2024-04-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resumeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileImage', models.ImageField(upload_to='static/image/')),
                ('FullName', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=50)),
                ('CareerObjective', models.TextField()),
                ('Skills', models.CharField(max_length=50)),
                ('Certifications', models.CharField(max_length=50)),
                ('Projects', models.CharField(max_length=50)),
                ('References', models.CharField(max_length=50)),
            ],
        ),
    ]
