# Generated by Django 5.0.4 on 2024-04-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='educationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('graduation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='workModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('StartDate', models.CharField(max_length=50)),
                ('EndDate', models.CharField(max_length=50)),
            ],
        ),
    ]
