# Generated by Django 5.0.4 on 2024-04-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0002_educationmodel_workmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='FullName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='FullName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='Degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='graduation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='institute',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='Certifications',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='EmailAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='FullName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='PhoneNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='ProfileImage',
            field=models.ImageField(null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='Projects',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='References',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='resumeinfomodel',
            name='Skills',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='Company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='EndDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='Position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='StartDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
