# Generated by Django 5.0.4 on 2024-05-05 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfBirth', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('Religion', models.CharField(max_length=50)),
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basicinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contactinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('PassingYear', models.CharField(max_length=50)),
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educationalinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperinceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('myUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
