# Generated by Django 5.0.4 on 2024-05-06 04:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0002_basicinfomodel_contactmodel_educationalmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='LastEducation',
            field=models.CharField(choices=[('jsc', 'JSC'), ('ssc', 'SSC'), ('hsc', 'HSC'), ('bsc', 'BSC')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
