# Generated by Django 5.0.4 on 2024-05-06 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0003_seekerprofilemodel_lasteducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='LastWork',
            field=models.CharField(choices=[('dipti', 'DIPTI'), ('dit', 'DIT')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
