# Generated by Django 5.0.4 on 2024-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0004_recruiterprofilemodel_lastwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodel',
            name='CGPA',
            field=models.CharField(default=2.5, max_length=50),
            preserve_default=False,
        ),
    ]
