# Generated by Django 5.0.4 on 2024-05-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0005_educationalmodel_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalmodel',
            name='Grade',
            field=models.CharField(default='A+', max_length=50),
            preserve_default=False,
        ),
    ]
