# Generated by Django 5.0.4 on 2024-05-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0007_educationalmodel_grade2'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperincemodel',
            name='Location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
