# Generated by Django 5.0.6 on 2024-05-26 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreSchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='UserType',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'teacher'), ('3', 'student')], max_length=100),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('StudentID', models.CharField(max_length=100)),
                ('UserType', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('male', 'Female')], max_length=100)),
                ('DateOB', models.DateField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Religion', models.CharField(max_length=100)),
                ('JoiningDate', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('AdmissionNumber', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('ConfirmPassword', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
                ('StudentImage', models.ImageField(upload_to='static/studentImg/')),
                ('FatherName', models.CharField(max_length=100)),
                ('FatherOccupation', models.CharField(max_length=100)),
                ('FatherMobile', models.CharField(max_length=100)),
                ('FatherEmail', models.EmailField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('MotherOccupation', models.CharField(max_length=100)),
                ('MotherMobile', models.CharField(max_length=100)),
                ('MotherEmail', models.EmailField(max_length=100)),
                ('PresentAddress', models.CharField(max_length=100)),
                ('PermanentAddress', models.CharField(max_length=100)),
                ('Added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
