# Generated by Django 5.0.6 on 2024-05-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreSchoolApp', '0002_alter_customeuser_usertype_studentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='AdmissionNumber',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='ConfirmPassword',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='StudentImage',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='UserType',
        ),
    ]
