# Generated by Django 5.0.3 on 2024-03-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
