# Generated by Django 5.0.3 on 2024-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='StudentImage',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
