# Generated by Django 5.0.4 on 2024-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('AboutMe', models.CharField(max_length=30)),
                ('Birth', models.CharField(max_length=30)),
            ],
        ),
    ]
