# Generated by Django 5.0.4 on 2024-04-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='Photo',
            field=models.ImageField(null=True, upload_to='static/img/my/'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='AboutMe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Title',
            field=models.TextField(null=True),
        ),
    ]
