# Generated by Django 5.0.4 on 2024-04-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_aboutmodel_photo_alter_aboutmodel_aboutme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmodel',
            old_name='Birth',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Degree',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='Phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='Photo',
            field=models.ImageField(null=True, upload_to='static/assets/img/my/'),
        ),
    ]
