# Generated by Django 5.0.4 on 2024-04-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_birth_aboutmodel_address_aboutmodel_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Degree', models.CharField(max_length=50)),
                ('Institute', models.CharField(max_length=50)),
                ('Session', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Background', models.ImageField(upload_to='static/assets/img/my/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
                ('Summary', models.TextField()),
            ],
        ),
    ]
