# Generated by Django 5.0.4 on 2024-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_educationmodel_homemodel_workmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='homemodel',
            name='Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='homemodel',
            name='ShortTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
