# Generated by Django 5.0.4 on 2024-05-09 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0002_alter_ecommerceuser_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.CreateModel(
            name='ContactInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('FacebookID', models.CharField(max_length=100)),
                ('EUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contactinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestedProduct', models.CharField(max_length=100)),
                ('ReferenceID', models.CharField(max_length=100)),
                ('EUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customerinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyAddress', models.CharField(max_length=100)),
                ('SellingExperience', models.CharField(max_length=100)),
                ('EUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellerinfomodel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
