# Generated by Django 5.0.4 on 2024-05-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0003_alter_ecommerceuser_gender_contactinfomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceuser',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ecommerceuser',
            name='UserType',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer')], max_length=100),
        ),
    ]
