# Generated by Django 5.0.4 on 2024-05-09 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerceApp', '0004_alter_ecommerceuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(choices=[('Electric', 'Electric'), ('Food', 'Food'), ('Beauty', 'Beauty')], max_length=100)),
                ('ProductDescription', models.TextField()),
                ('ProCompanyName', models.CharField(max_length=100)),
                ('ProCompanyAddress', models.CharField(max_length=100)),
                ('ProductPrice', models.CharField(max_length=100)),
                ('Added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
