# Generated by Django 5.0.3 on 2024-03-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=100)),
                ('classid', models.CharField(max_length=100)),
                ('totalstudent', models.CharField(max_length=100)),
            ],
        ),
    ]
