# Generated by Django 5.0.3 on 2024-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreName', models.CharField(max_length=30)),
                ('OwnerName', models.CharField(max_length=50)),
                ('StoreLocation', models.CharField(max_length=30)),
            ],
        ),
    ]
