# Generated by Django 5.0.6 on 2024-06-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['username'], 'verbose_name': 'Shakil'},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='To_Do_Table',
        ),
    ]
