# Generated by Django 5.0.6 on 2024-06-09 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'ordering': ['username'], 'verbose_name': 'Custom User'},
        ),
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['category']},
        ),
        migrations.AlterUniqueTogether(
            name='customusermodel',
            unique_together={('username', 'email')},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='To_Do_List_Table',
        ),
    ]
