# Generated by Django 5.0.4 on 2024-04-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjobmodel',
            name='Deadline',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Designation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Experience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobTitle',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Qualification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
