# Generated by Django 5.0.4 on 2024-04-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
