# Generated by Django 5.0.4 on 2024-04-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0002_remove_custom_user_confirmpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='blood_group',
            field=models.CharField(choices=[('a+', 'A+'), ('b+', 'B+'), ('o+', 'O+'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='fathername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='mothername',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='profileimg',
            field=models.ImageField(null=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='displayname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobseekter', 'JobSeekter')], max_length=100, null=True),
        ),
    ]
