# Generated by Django 5.0.4 on 2024-04-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0002_addjobmodel_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobmodel',
            name='CompanyName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='JobTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjobmodel',
            name='Salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
