# Generated by Django 5.0.4 on 2024-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0004_alter_custom_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=50)),
                ('CompanyName', models.CharField(max_length=50)),
                ('CompanyDescription', models.TextField()),
                ('JobDescription', models.TextField()),
                ('Qualification', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=50)),
            ],
        ),
    ]
