# Generated by Django 5.0.3 on 2024-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('About', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Mobile', models.CharField(max_length=250)),
                ('Picture', models.ImageField(upload_to='media/images/')),
                ('Summary', models.CharField(max_length=250)),
                ('Degree', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('University', models.CharField(max_length=50)),
                ('Session', models.CharField(max_length=50)),
                ('WorkPlace', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('ProgrammingSkill', models.CharField(max_length=50)),
                ('Other', models.CharField(max_length=50)),
            ],
        ),
    ]
