# Generated by Django 5.0.4 on 2024-04-29 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeApp', '0002_remove_viewersprofilemodel_myuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Profile_Img', models.ImageField(upload_to='static/prfile_img/')),
                ('userData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='viewersProfileModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest', models.CharField(max_length=100)),
                ('Profile_Img', models.ImageField(upload_to='static/prfile_img/')),
                ('userData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
