# Generated by Django 5.0.3 on 2024-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backendProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backendprogramname', models.CharField(max_length=100)),
                ('backendprogramid', models.CharField(max_length=100)),
                ('backendpopularcountry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='badProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badprogramname', models.CharField(max_length=100)),
                ('badprogramid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='frontendProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontendprogramname', models.CharField(max_length=100)),
                ('frontendprogramid', models.CharField(max_length=100)),
                ('frontendpopularcountry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='popularProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularprogramname', models.CharField(max_length=100)),
                ('popularprogramid', models.CharField(max_length=100)),
                ('popularprogramcountry', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='progrmmingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmingname', models.CharField(max_length=100)),
                ('programmingid', models.CharField(max_length=100)),
                ('programmingcategory', models.CharField(max_length=100)),
            ],
        ),
    ]
