# Generated by Django 5.0.3 on 2024-03-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=50)),
                ('teacherid', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
