# Generated by Django 5.0.3 on 2024-03-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_teachermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='libraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libraryid', models.CharField(max_length=20)),
                ('librarylocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='managementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managementid', models.CharField(max_length=20)),
                ('managementname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='staffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffid', models.CharField(max_length=20)),
                ('staffname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
