# Generated by Django 5.0.3 on 2024-03-20 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_librarymodel_managementmodel_staffmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='designation',
            new_name='teacherdesignation',
        ),
    ]
